pub mod agent_runtime;
pub mod browser;
pub mod capture;
pub mod computer;
pub mod context;
pub mod credentials;
pub mod images;
/// 往批准过的窗口里注入一次点击。这个产品里最狠的能力，形状见模块文档。
pub mod input;
pub mod llm_client;
pub mod llm_profiles;
pub mod mcp;
pub mod problem_parser;
pub mod project_memory;
pub mod project_tasks;
pub mod verification;
/// 取一个网址的正文给模型看：URL 校验、跳转策略、正文提取。形状见模块文档。
pub mod web_fetch;
pub mod workspace;
